<?php

/**
 * This is the model base class for the table "post".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Post".
 *
 * Columns in table "post" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $user_owner
 * @property string $title
 * @property string $description
 * @property string $category
 * @property string $datetime
 *
 */
abstract class BasePost extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'post';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Post|Posts', $n);
	}

	public static function representingColumn() {
		return 'user_owner';
	}

	public function rules() {
		return array(
			array('user_owner, title, description, category, datetime', 'required'),
			array('user_owner, category', 'length', 'max'=>50),
			array('title', 'length', 'max'=>100),
			array('description', 'length', 'max'=>250),
			array('id, user_owner, title, description, category, datetime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_owner' => Yii::t('app', 'User Owner'),
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'category' => Yii::t('app', 'Category'),
			'datetime' => Yii::t('app', 'Datetime'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		
		$criteria->compare('id', $this->id);
		$criteria->compare('user_owner', $this->user_owner, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('category', $this->category, true);
		$criteria->compare('datetime', $this->datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,			
		));
	}
}